Support adding users to projects via the API
ibutsu/ibutsu-server pull request #240
Opened 2021-11-17 16:37 UTC by john-dupuy

Allow users to be added to projects by the API:
- This is done by sending a list of usernames (emails) in the request body, e.g.

```json
{
  "users": ["jdupuy@redhat.com", "jdoe@blah.com", "jdeer@redhat.com"]
}
```
If the user does not exist in the DB, they won't be added. If the user is already in the project, they won't be added. 

Depends on #237

2021-11-17 20:57 UTC, rsnyman requested changes
Just one minor thing.

2021-11-17 20:57 UTC, rsnyman commented on backend/ibutsu_server/controllers/project_controller.py
> +    if not user.is_superadmin:
You could collapse this into a single `if`

```suggestion
    if not user.is_superadmin and project and project.owner.id != user.id:
```

2021-11-18 17:51 UTC, john-dupuy commented
The frontend build appears to be failing due to https://github.com/greatSumini/react-facebook-login/issues/74

2021-11-19 16:19 UTC, rsnyman approved these changes

2021-11-19 16:19 UTC, merged