Adding ability to edit dashboard widgets
ibutsu/ibutsu-server pull request #412
Opened 2022-11-30 17:26 UTC by Griffin-Sullivan

Solving https://github.com/ibutsu/ibutsu-server/issues/389

This PR adds a button to each widget for editing the widget. When the button is clicked a Modal pops up with the fields already filled out with the widgets details. Users can then make changes and click save. Note: All edits will shown on save except for the widget's title. For some reason it only updates on a full page refresh. I can look into this more. 

Everything else is working correctly, but I have this error in the console that I can't track down in the code. 
![Screenshot from 2022-11-30 12-23-05](https://user-images.githubusercontent.com/48397354/204866111-2e7c80d9-f120-4c0b-aca2-a43bc56e8041.png)

2022-11-30 21:34 UTC, rsnyman requested changes

2022-11-30 21:34 UTC, rsnyman commented on frontend/src/dashboard.js
> +        : ''}
You don't need the this. Just put the `EditWidgetModal` in the page. The `isEditModalOpen` value determines whether or not it is visible. This way you have less render cycles.

2022-12-01 16:01 UTC, Griffin-Sullivan commented on frontend/src/dashboard.js
> +        : ''}
So the reason I'm doing it this way is because we have to update the `EditWidgetModal` with the values we are passing into props as `data`. In the constructor I pull the values out of `props.data` to be the default value in the text inputs. If I just put the `EditWidgetModal` on the page, it will bring up a broken modal with missing param Text Inputs and no values in the fields, because when it's rendered we still haven't selected a widget. 

Are there better ways to do this? If I try to force the value of the input fields to be what's in `props.data` it doesn't let you change the text.

2022-12-01 17:59 UTC, rsnyman commented on frontend/src/dashboard.js
> +        : ''}
Hrm. [This answer](https://stackoverflow.com/a/53062164) on Stack Overflow might help?

2022-12-02 14:18 UTC, Griffin-Sullivan commented on frontend/src/dashboard.js
> +        : ''}
That didn't work, but I did find [this](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-controlled-component). That would require me to move every state variable and `onChange` method in `EditWidgetModal` to `dashboard.js` and control the entire component from the parent. Would you prefer that over my current implementation?

2022-12-05 15:39 UTC, rsnyman commented on frontend/src/dashboard.js
> +        : ''}
I'm wondering how we do it in other places, like the admin pages, let me have a look.

2022-12-05 15:44 UTC, rsnyman approved these changes

2022-12-05 15:44 UTC, merged