New filter-heatmap widget for making flexible heatmaps
ibutsu/ibutsu-server pull request #428
Opened 2023-02-22 17:24 UTC by Griffin-Sullivan

Adding a new widget for a heatmap that collects runs based off of a filter. Users can specify a list of filters, number of builds, and a group_field to get a heatmap of runs that fit those parameters. Open to suggestions especially on how I implemented the backend. I sort of had to retrieve all of the most recent run results and then manually filter them to make sure they're in the right order and then only return x amount of runs based on what the user passed for builds. Frontend is pretty much the exact same as jenkins-heatmap.

2023-02-28 18:52 UTC, rsnyman requested changes
Overall, this looks good. I'd like to drop the "count skips as fails/passes" since this doesn't actually make any sense, and I'd like to make the Jenkins heatmap a sort of a type of filter heatmap.

I also just want to test this out manually, locally before giving the final go-ahead.

2023-02-28 18:52 UTC, rsnyman commented on backend/ibutsu_server/constants.py
> +            },
Let's drop this, don't count skips against the pass rate.

2023-02-28 18:52 UTC, rsnyman commented on frontend/src/dashboard.js
> +                      <JenkinsHeatmapWidget
We should actually switch these around, convert the `JenkinsHeatmapWidget` to a `FilterHeatmapWidget` and then make the Jenkins heatmap use the `FilterHeatmapWidget`

2023-03-01 15:00 UTC, j0nallen commented
@Griffin-Sullivan Could this be a solution to [https://github.com/ibutsu/ibutsu-server/issues/411](https://github.com/ibutsu/ibutsu-server/issues/411)?

2023-03-01 15:03 UTC, Griffin-Sullivan commented
> @Griffin-Sullivan Could this be a solution to #411?

@j0nallen I believe so! I was unaware of that issue, but it seems like this will cover that use case.

2023-03-01 21:53 UTC, j0nallen commented
Thanks, @Griffin-Sullivan - will try this out and see!

2023-03-13 16:59 UTC, merged