Update the migration script to work with new psql db
ibutsu/ibutsu-server pull request #47
Opened 2020-09-28 19:30 UTC by john-dupuy

2020-09-29 21:43 UTC, john-dupuy commented
The foreign key constraint is causing some problems with bad data in my local database, I don't think we'll hit the same issues on prod (especially if we're ignoring the old stuff) but I just pulled the latest DB dump to test out tomorrow.

2020-09-30 17:19 UTC, rsnyman commented on backend/ibutsu_server/db/models.py
> +    upload_date = Column(DateTime)
If you need to make a default value for this, you can do the following:

```suggestion
    upload_date = Column(DateTime, default=datetime.utcnow)
```

2020-09-30 17:21 UTC, rsnyman commented on backend/ibutsu_server/scripts/mongo2postgres.py
> +        "CREATE INDEX results_env ON results(env);",
Indexes on individual columns can (and should) be created on the models. For example:

```python
class Result(Model):
    env = Column(String, index=True)
```

2020-09-30 17:23 UTC, rsnyman commented on backend/ibutsu_server/scripts/mongo2postgres.py
> +    if Model.__tablename__ == "runs" or Model.__tablename__ == "results":
```suggestion
    if Model.__tablename__ in ["runs", "results"]:
```

2020-09-30 17:26 UTC, rsnyman commented on backend/ibutsu_server/scripts/mongo2postgres.py
> +    if Model.__tablename__ == "runs" or Model.__tablename__ == "results":
```suggestion
    if Model.__tablename__ in ["runs", "results"]:
```

2020-09-30 17:28 UTC, rsnyman requested changes
I made a couple suggestions :-)

2020-10-02 18:34 UTC, rsnyman approved these changes

2020-10-05 15:29 UTC, john-dupuy commented
OK @rsnyman I think this is finally in the "final" state. I applied a similar logic for the artifact files that is done for the results so that we can avoid any foreign key constraint errors (i.e. getting a list of migrated results and searching for artifacts within that result list).

2020-10-05 16:38 UTC, rsnyman approved these changes

2020-10-05 16:38 UTC, merged